import { v4 } from "uuid";

export const matches = [
  {
    id: v4(),
    leagueTitle: "La Liga",
    leagueAbbv: "ES",
    country: "Spain",
    leagueMatches: [
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
    ],
  },

  {
    id: v4(),
    leagueTitle: "Premier League",
    leagueAbbv: "GB",
    country: "England",
    leagueMatches: [
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
      {
        id: v4(),
        homeClub: "Barcelona",
        awayClub: "Real Madrid",
        homeClubScore: 1,
        awayClubScore: 0,
        time: "18:30",
        oneOdd: "2.50",
        xOdd: "3.25",
        twoOdd: "2.90",
      },
    ],
  },
];
